# sonar-project.properties
sonar.projectKey=easterbuunny_easterbuunny.github.io
sonar.organization=easterbuunny

# Dossiers à analyser (votre code source)
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**

# Dossiers contenant les tests (si vous en avez)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
