# sonar-project.properties
sonar.projectKey=easterbuunny_portfolio # À modifier avec la clé générée sur SonarCloud
sonar.organization=easterbuunny        # À modifier avec votre ID d'orga SonarCloud

# Dossiers à analyser (votre code source)
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**

# Dossiers contenant les tests (si vous en avez)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
