server.port=8000
spring.application.name=clean-backend
# Configuration H2 pour le POC
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Par défaut, on lance le profil de développement en local
spring.profiles.active=dev
app.cors.origins=http://localhost:4000

