name: CI - Code Quality & Security

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "main", "develop" ]

jobs:
  # ----------------------------------------------------
  # JOB 1 : Analyse SonarQube
  # ----------------------------------------------------
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Historique complet nécessaire pour Sonar

      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # ----------------------------------------------------
  # JOB 2 : Analyse de Sécurité (CodeQL SAST)
  # ----------------------------------------------------
  security-codeql:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write # Permet d'afficher les failles dans l'onglet "Security" de GitHub

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Initialiser CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript # Angular utilise TypeScript

      - name: Lancer l'analyse CodeQL
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"
