name: Déploiement du Portfolio Angular

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Installer les dépendances
        run: npm ci

      - name: Compiler le projet Angular
        run: npx ng build --configuration production --base-href /

      - name: Fixer le routage (Copie vers 404.html)
      # Remplace ./dist/portfolio par le même chemin que tu utilises dans publish_dir !
        run: cp ./dist/portfolio/index.html ./dist/portfolio/404.html

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio/browser
